spring:
  profiles:
    active: dev
server:
  port: 8201

eureka:
  instance:
    instance-id: config_client.com
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
info:
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $articleId$
  build.version: $version$
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

---
spring:
  profiles: dev
  application:
    name: microcloud-config-dev
eureka: #一定要编写eureka的地址
  client: #目的是为了客户端可以通过eureka找到sringcloudconfig微服务
    service-url:
      defaultZone: http://eureka-7301.com:7301/eureka

---
spring:
  profiles: beta
  application:
    name: microcloud-config-beta
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7301.com:7301/eureka
