spring:
  profiles:
    active: dev
server:
  port: 8201

#eureka:
#  client:
#    service-url:
#      defaultZone: http://mldnjava:hello@eureka-7001.com:7001/eureka,http://mldnjava:hello@eureka-7002.com:7002/eureka,http://mldnjava:hello@eureka-7003.com:7003/eureka
  instance:
    instance-id: config_client.com
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
info:
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $articleId$
  build.version: $version$
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

---
spring:
  profiles: dev
  application:
    name: microcloud-config-dev
eureka:
  client:
    service-url:
      defaultZone: http://mldnjava:hello@eureka-7001.com:7001/eureka,http://mldnjava:hello@eureka-7003.com:7003/eureka

---
spring:
  profiles: beta
  application:
    name: microcloud-config-dev
eureka:
  client:
    service-url:
      defaultZone: http://mldnjava:hello@eureka-7001.com:7001/eureka
